### ISSUE TITLE
Font Family select broken in Dark theme on Firefox

### ISSUE THREAD

**Issue by huphtur** [tailzilla/tailzilla-app#1]
On Firefox 80, with Dark theme enabled, the Font Family select doesn't show the options, only when hovered over an option.

![ffs](https://user-images.githubusercontent.com/469438/92397200-412a0b80-f0db-11ea-8350-15d410ce7adc.png)

**Comment by tranbathanhtung** [comment]
Fixed ... Thanks for your report  😄
