### ISSUE TITLE
Turn tailzilla into interactive video 

### ISSUE THREAD

**Issue by steveyang331** [tailzilla/tailzilla-app#4]
If you know scrimba , you'll got idea to tailzilla, turn tailzilla into interactive video 

https://scrimba.com/ Scrimba is the next-generation platform for learning how to code. Our screencasts enable **you to interact with the code directly in the player.**

**Comment by tranbathanhtung** [comment]
Basically, the target of tailzilla and scrimba is different ... So, this feature I feel isn't suitable for implementation.

**Comment by steveyang331** [comment]
Yeah. this is just an idea. nevermind .close it . it's ok.
